jenkins:
  systemMessage: "Running jenkins.yaml to setup Jenkins"
  numExecutors: 2

  # Security configuration
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "happyyear27"
          description: "Jenkins Administrator"

  authorizationStrategy:
  globalMatrix:
    permissions:
      - "Overall/Administer:admin"
      - "Credentials/View:admin"
      - "Credentials/Create:admin"
      - "Credentials/Update:admin"
      - "Credentials/Delete:admin"
      - "Credentials/ManageDomains:admin"
      - "Job/Read:admin"
      - "Job/Configure:admin"
      - "Job/Build:admin"

  remotingSecurity:
    enabled: true

  mode: NORMAL
  labelString: ""

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

# Global tool configuration
tool:
  git:
    installations:
      - name: "Git"
        home: "/usr/bin/git"

  nodejs:
    installations:
      - name: "NodeJS"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "22.9.0"
                    npmPackagesRefreshHours: 72

# Configure global settings
unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@localhost"
  timestamper:
    allPipelines: true

jobs:
  - script: >
      pipelineJob('autoBuildDockerimageAndPushToDockerhub') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/huymusic987/COSC2767-RMIT-Store.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          githubPush()
        }
      }
